# Generated by Django 5.1.7 on 2025-03-24 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Сылка на категорию')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Названия поста')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categories', verbose_name='Категория поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.DeleteModel(
            name='Bb',
        ),
    ]
